ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)
Syntax Error while loading YAML.
  did not find expected key
The error appears to be in '/runner/project/playbook-start.yaml': line 38, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
      # Notez l'alignement correct ici, ceci devrait être au même niveau que les autres tâches au sein du bloc.
      - name: Exécution du Script de démarrage de Tomcat
      ^ here
